kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: permissionforsa
  namespace: {{ .Values.serviceMesh.controlPlane.namespace }}
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

